# *** This Dockefile is generated by KloverCloud. You can modify it based on your application requirements *** #

FROM klovercloud/node:13-slim

RUN useradd -ms /bin/bash klovercloud

WORKDIR /home/klovercloud

COPY . .


EXPOSE 8080

EXPOSE 8081


USER klovercloud


